development:
  adapter:  postgresql
  database: loedash_dev
  pool:     5
  timeout:  5000
  host:     localhost

test:
  adapter:  postgresql
  database: loedash_test
  pool:     5
  timeout:  5000
  host:     localhost

production:
  adapter:  postgresql
  database: loedash_prod
  pool:     5
  timeout:  5000
  host:     localhost
