# Socrata settings
default: &default
  datasets:
  - id: 4h79-gcxp
    name: LOE All Inspections
  - id: 26hs-mxmu
    name: LOE All Violations
  - id: whix-gx4j
    name: LOE All Cases
  - id: v5t4-gjta
    name: LOE Case History
  domain: data.greensboro-nc.gov
  app_token: <%= ENV['SOCRATA_TOKEN'] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
